on:
  push:
    branches:
      - master

name: Create Slate Documentation on Push

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build documentation
      uses: docker://passfort/slate-builder-action:latest
      env:
        DOC_BASE_FOLDER: source
        ZIP_BUILD: false

    - name: Deploy to GitHub Pages
      uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: source/build
        # The builtin GITHUB_TOKEN doesn't seem to have write capability on gh-pages branch
        GH_PAT: ${{ secrets.GH_PAT }}
